workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: youbrief.xcworkspace
        XCODE_SCHEME: youbriefScheme
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Run tests
        script: xcodebuild test -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' ONLY_ACTIVE_ARCH=YES
      - name: Build IPA
        script: xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $HOME/build/$XCODE_SCHEME.xcarchive
      - name: Export IPA
        script: xcodebuild -exportArchive -archivePath $HOME/build/$XCODE_SCHEME.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $HOME/build
    artifacts:
      - $HOME/build/*.ipa
      - $HOME/build/*.xcarchive
    publishing:
      email:
        recipients:
          - shreyansh@liftoffllc.com
